### ISSUE TITLE
Compatibility trouble with protocolLib

### ISSUE THREAD

**Issue by Guarmanda** [MundoSK/MundoSK#10]
The last mundosk build doesn't work with the last protocolLib build, and having mundosk and protocollib prevents skript to work. Having mundosk alone doesn't cause any problem, and having protocollib alone doesn't cause any problem (but I need the both)
Here's the error:
```[11:40:14] [Server thread/WARN]: [Skript] Task #19 for Skript v2.2-dev30d generated an exception
java.lang.NoClassDefFoundError: com/comphenix/protocol/reflect/ObjectEnum
	at com.pie.tlatoani.Mundo$24.parse(Mundo.java:566) ~[?:?]
	at com.pie.tlatoani.Mundo$24.parse(Mundo.java:563) ~[?:?]
	at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:420) ~[?:?]
	at ch.njol.skript.registrations.Classes.parse(Classes.java:449) ~[?:?]
	at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:95) ~[?:?]
	at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:84) ~[?:?]
	at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:1) ~[?:?]
	at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:179) ~[?:?]
	at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:130) ~[?:?]
	at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:251) ~[?:?]
	at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178) ~[?:?]
	at ch.njol.skript.lang.Condition.parse(Condition.java:81) ~[?:?]
	at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:921) ~[?:?]
	at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54) ~[?:?]
	at ch.njol.skript.lang.Conditional.<init>(Conditional.java:44) ~[?:?]
	at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:928) ~[?:?]
	at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54) ~[?:?]
	at ch.njol.skript.lang.Conditional.<init>(Conditional.java:44) ~[?:?]
	at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:928) ~[?:?]
	at ch.njol.skript.command.Commands.loadCommand(Commands.java:471) ~[?:?]
	at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:526) ~[?:?]
	at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:333) ~[?:?]
	at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:345) ~[?:?]
	at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:275) ~[?:?]
	at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:305) ~[?:?]
	at ch.njol.skript.Skript$2.run(Skript.java:410) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-65e8124-8bf06d6]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-65e8124-8bf06d6]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-65e8124-8bf06d6]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-65e8124-8bf06d6]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-65e8124-8bf06d6]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.reflect.ObjectEnum
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-65e8124-8bf06d6]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
	... 33 more```

**Comment by TlatoaniHJ** [comment]
Try updating to the latest BETA version of MundoSK, the download link is available on MundoSK's Overview section on skUnity Forums.

**Comment by Guarmanda** [comment]
oh, thanks
