### ISSUE TITLE
Can't load MundoSK

### ISSUE THREAD

**Issue by Xentax5** [MundoSK/MundoSK#17]
### Bug Report

Skript Version: 2.2 (V9b)

MundoSK Version: 1.8.4

Minecraft Version: Spigot 1.8.8

### Steps to Reproduce the Issue
Hello, my problem is that, when i put MundoSK in my plugins folder and start the server I get error "Is it up to date?". Config files generated, so i tried disabling everything, that can be disabled, but it still doesn't work.

### Console Errors (if applicable)
```
[16:50:26 INFO]: [MundoSK] Enabling MundoSK v1.8.4
[16:50:26 INFO]: [MundoSK] No worlds were assigned to load automatically
[16:50:26 INFO]: [MundoSK] Pie is awesome :D
[16:50:26 ERROR]: Error occurred while enabling MundoSK v1.8.4 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/generator/ChunkGenerator$ChunkData
at com.pie.tlatoani.Generator.GeneratorManager.load(GeneratorManager.java:22) ~[?:?]
at com.pie.tlatoani.Mundo$$Lambda$34/49370145.run(Unknown Source) ~[?:?]
at com.pie.tlatoani.Registration.Registration.register(Registration.java:29) ~[?:?]
at com.pie.tlatoani.Mundo.onEnable(Mundo.java:72) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356) [minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.ClassNotFoundException: org.bukkit.generator.ChunkGenerator$ChunkData
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[minecraft_server.jar:git-Spigot-f94fe8f-2642f9b]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
... 15 more
```

### Other Useful Info (ex. addons and plugins you are using)
Plugin list with versions:
```
plugins (69): AdvancedBan (9), AsyncWorldEdit (2.2.2), AsyncWorldEditInjector (2.2.2), AuthMe (${version}), AuthMeSkAddon (1.1), BossShop (2.0.4), ChestShop (3.8.12), Citizens (2.0.16-SNAPSHOT (build 1247)),
 CleanroomGenerator (1.0.0), CoreProtect (2.12.0), CreativeGates (2.8.0), DispenserRefill (1.1.0-A4), DynColor (1.2), EffectLib (3.6), EggRenade (2.1.2), Essentials (TeamCity), EssentialsChat (TeamCity), ExtrasSK (1.1), 
FactionChat (1.9.10), Factions (2.8.2), FakaHedaMinequery (1.7), FrameProtect (2.5), GAListener (1.3.1), 
HolographicDisplays (2.1.10), Itemizer (1.4.8), LibsDisguises (8.6.2), LightAPI (3.2.5), LogBlock (1.94), MassiveCore (2.8.2), mmSkriptAddon (0.92a), Multiverse-Core (2.5-b708), Multiverse-Portals (2.5-b725), MundoSK (1.8.4),
 MyCommand (5.1.6), MythicMobs (4.3.2-SNAPSHOT), OpenInv (2.3.2), PermissionsEx (1.23.4), PlayerHeads (3.8-jenkins-PlayerHeads-1-48-ged24b6b), PlayTimeV2 (0.6), PlugMan (2.0.8), ProtocolLib (3.6.5), Quests (2.7.6-b${env.BUILD_NUMBER}), 
RandomSK (2.7.1), Realistic_World (1.9.2.1), Residence (2.6.7.0), Sentry (1.8.5), SharpSK (1.6.3), Shopkeepers (1.82), SimpleTrading (1.4), skDragon (0.14.0), Skellett (1.9.5), SkinsRestorer (12.9.9), SkMorkaz (0.21), 
SkQuery (3.21.4), skRayFall (1.9.5), Skript (2.2-Fixes-V9b), SkStuff (1.6.4.1), skUtilities (0.8.9), TreasureChest (8.4.4), TuSKe (1.5.7), Umbaska (2.0 Beta 4), UUID (2.8.4), Vault (1.5.3-b37), ViaVersion (1.0.3),
Votifier (2.3.3), WildSkript (1.9), WorldBorder (1.8.4), WorldEdit (6.1;no_git_id), WorldGuard (6.2.1;84bc322)
```

**Comment by Snow-Pyon** [comment]
Could you tell us where you downloaded that version of Spigot?

**Comment by Xentax5** [comment]
With build tools?

**Comment by TlatoaniHJ** [comment]
Try using BuildTools to get a new 1.8.8 jar and see if that fixes the issue.

**Comment by Xentax5** [comment]
Yeah, lol thank you. It seems working now. Got a little spam in console like:
`[11:09:39 WARN]: Tried to add entity null that already exists with UUID 468db3a9-6710-286b-8be6-73a37d7dbf71`
But i guess that's because of changing the version while the worlds remain same.
I was probably using some outdated/develop version. Thank you :)
