### ISSUE TITLE
NPE when setting nametag of a null player

### ISSUE THREAD

**Issue by kh498** [MundoSK/MundoSK#19]
### Bug Report

Skript Version: `2.2-dev34`

MundoSK Version: `1.8.5`

Minecraft Version: `1.8.8`

### Steps to Reproduce the Issue

`set {_p}'s nametag for {_p2} to "%{_p}%"`

let `{_p}` and `{_p2}` be `null`

### Console Errors (if applicable)
```
[00:38:09 ERROR]: #!#!
[00:38:09 ERROR]: #!#! [Skript] Severe Error:
[00:38:09 ERROR]: #!#!
[00:38:09 ERROR]: #!#! Something went horribly wrong with Skript.
[00:38:09 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[00:38:09 ERROR]: #!#! Your Minecraft version or server software appears to be unsupported by Skript (bensku's version).
[00:38:09 ERROR]: #!#! Currently only supported servers are Spigot and its forks for Minecraft 1.9 or newer.
[00:38:09 ERROR]: #!#! Other versions might work, but since you're getting this error message something is NOT working,
[00:38:09 ERROR]: #!#! nor it will work, unless you switch to supported platform.
[00:38:09 ERROR]: #!#! Issue tracker: https://github.com/bensku/Skript/issues (only if you know what you're doing!)
[00:38:09 ERROR]: #!#!
[00:38:09 ERROR]: #!#! Stack trace:
[00:38:09 ERROR]: #!#! java.lang.NullPointerException
[00:38:09 ERROR]: #!#!     at com.pie.tlatoani.Skin.ExprNameTagOfPlayer.change(ExprNameTagOfPlayer.java:75)
[00:38:09 ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:271)
[00:38:09 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[00:38:09 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[00:38:09 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[00:38:09 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[00:38:09 ERROR]: #!#!     at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:95)
[00:38:09 ERROR]: #!#!     at ch.njol.skript.lang.function.Function.execute(Function.java:112)
[00:38:09 ERROR]: #!#!     at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:193)
[00:38:09 ERROR]: #!#!     at ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:53)
[00:38:09 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[00:38:09 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[00:38:09 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[00:38:09 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[00:38:09 ERROR]: #!#!     at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:95)
[00:38:09 ERROR]: #!#!     at ch.njol.skript.lang.function.Function.execute(Function.java:112)
[00:38:09 ERROR]: #!#!     at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:193)
[00:38:09 ERROR]: #!#!     at ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:53)
[00:38:09 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[00:38:09 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[00:38:09 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[00:38:09 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[00:38:09 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:279)
[00:38:09 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:236)
[00:38:09 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:255)
[00:38:09 ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:170)
[00:38:09 ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:38:09 ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[00:38:09 ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[00:38:09 ERROR]: #!#!     at java.lang.reflect.Method.invoke(Unknown Source)
[00:38:09 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
[00:38:09 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[00:38:09 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[00:38:09 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
[00:38:09 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
[00:38:09 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1181)
[00:38:09 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001)
[00:38:09 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[00:38:09 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[00:38:09 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[00:38:09 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[00:38:09 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[00:38:09 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[00:38:09 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
[00:38:09 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[00:38:09 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[00:38:09 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[00:38:09 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[00:38:09 ERROR]: #!#!
[00:38:09 ERROR]: #!#! Version Information:
[00:38:09 ERROR]: #!#!   Skript: 2.2-dev34
[00:38:09 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[00:38:09 ERROR]: #!#!   Minecraft: 1.8.8
[00:38:09 ERROR]: #!#!   Java: 1.8.0_162 (Java HotSpot(TM) 64-Bit Server VM 25.162-b12)
[00:38:09 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[00:38:09 ERROR]: #!#!
[00:38:09 ERROR]: #!#! Server platform: Paper
[00:38:09 ERROR]: #!#!
[00:38:09 ERROR]: #!#! Current node: null
[00:38:09 ERROR]: #!#! Current item: set {_p}'s nametag for {_p2} to "%{_p}(as java.lang.Object)%"
[00:38:09 ERROR]: #!#! Thread: Server thread
[00:38:09 ERROR]: #!#!
[00:38:09 ERROR]: #!#! Language: english
[00:38:09 ERROR]: #!#! Link parse mode: DISABLED
[00:38:09 ERROR]: #!#!
[00:38:09 ERROR]: #!#! End of Error.
```

### Other Useful Info (ex. addons and plugins you are using)

Simple fix is to check if `player` is  `null` [here](https://github.com/MundoSK/MundoSK/blob/ccc78e18e6d8e97c5c9aabd43865be8a0f9169c3/src/com/pie/tlatoani/Skin/ExprNameTagOfPlayer.java#L75)

**Comment by TlatoaniHJ** [comment]
Fix planned for MundoSK 1.8.6.
