### ISSUE TITLE
MundoSK broke in dev37c

### ISSUE THREAD

**Issue by TrademarkTM** [MundoSK/MundoSK#22]
### Bug Report

Skript Version: dev37c

MundoSK Version: 1.8.6 beta 19

Minecraft Version: 1.12.2

### Steps to Reproduce the Issue
Turn on the server

### Full Code
No code needed, it just breaks

### Errors on Reload (if applicable)
```
[10:41:29] [Server thread/ERROR]: Error occurred while enabling MundoSK v1.8.6-BETA.29 (Is it up to date?)
java.lang.NoSuchMethodError: ch.njol.skript.lang.SyntaxElementInfo.<init>([Ljava/lang/String;Ljava/lang/Class;)V
	at com.pie.tlatoani.Core.Registration.ModifiableSyntaxElementInfo$Effect.<init>(ModifiableSyntaxElementInfo.java:57) ~[?:?]
	at com.pie.tlatoani.ListUtil.ListUtil.load(ListUtil.java:41) ~[?:?]
	at com.pie.tlatoani.Core.Registration.Registration.register(Registration.java:32) ~[?:?]
	at com.pie.tlatoani.Mundo.onEnable(Mundo.java:75) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
```

### Console Errors (if applicable)
^^

### Other Useful Info (ex. addons and plugins you are using)
skQuery, Skript, skript-mirror

Hope this can be fixed soon!
Thanks!

**Comment by TlatoaniHJ** [comment]
This should be fixed in MundoSK 1.8.6-BETA.36. Issue will be closed when MundoSK 1.8.6 is released.
