### ISSUE TITLE
Error occured while enabling MundoSK v1.8.5

### ISSUE THREAD

**Issue by Hitman77600** [MundoSK/MundoSK#25]
### Bug Report

Skript Version: v2.2-dev37c

MundoSK Version: 1.8.5

Minecraft Version: 1.11.2

### Problem
Error occurred while enabling MundoSK v1.8.5 (Is it up to date?)
java.lang.NoSuchMethodError: ch.njol.skript.lang.SyntaxElementInfo.<init>([Ljava/lang/String;Ljava/lang/Class;)V
	at com.pie.tlatoani.Registration.ModifiableSyntaxElementInfo$Effect.<init>(ModifiableSyntaxElementInfo.java:57) ~[?:?]
	at com.pie.tlatoani.ListUtil.ListUtil.load(ListUtil.java:41) ~[?:?]
	at com.pie.tlatoani.Registration.Registration.register(Registration.java:29) ~[?:?]
	at com.pie.tlatoani.Mundo.onEnable(Mundo.java:80) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
[20:43:19] [Server thread/INFO]: [SQLibrary] Enabling SQLibrary v7.1

### Other Useful Info (ex. addons and plugins you are using)
reqn-1.2.1, SkDragon-0.14.0, Skellett, SkQuery, SkRayFall, skript-yaml, SkStuff, SkUtilities

### Troubleshooting

Have you tried looking in the documentation: Yep

Have you tried looking in the forums: Yep, everything talk about other problem

What other methods have you tried to fix it: 

Change server version at last version and didn't work.
For information i use spigot 1.11.2, and my server run on offline mode.

**Comment by Hitman77600** [comment]
Oops sorry, down of my issue, it's maybe because skript version dev37c

**Comment by TlatoaniHJ** [comment]
Same as #22. Downloads for MundoSK beta versions are available here on GitHub.
