### ISSUE TITLE
1.14.1doesn't even let me join

### ISSUE THREAD

**Issue by Hyaoo** [MundoSK/MundoSK#29]
### Bug Report

Skript Version: 2.3.2

MundoSK Version: 1.8.6-BETA.57

Minecraft Version: 1.14.1

### Steps to Reproduce the Issue
Join game

### Full Code
none

### Console Errors (if applicable)
`[13:38:30] [Server thread/WARN]: [MundoSK] Task #39 for MundoSK v1.8.6-BETA.57 generated an exception
java.lang.IllegalArgumentException: The player parameter in add(Player player) must be non-null and online, player: CraftPlayer{name=Benchanter}
        at com.pie.tlatoani.Tablist.Group.TablistGroup.add(TablistGroup.java:56) ~[?:?]
        at com.pie.tlatoani.Tablist.TablistManager.lambda$onJoin$2(TablistManager.java:112) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-03bd4b0-fcb9f90]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot.jar:git-Spigot-03bd4b0-fcb9f90]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1008) [spigot.jar:git-Spigot-03bd4b0-fcb9f90]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot.jar:git-Spigot-03bd4b0-fcb9f90]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [spigot.jar:git-Spigot-03bd4b0-fcb9f90]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [spigot.jar:git-Spigot-03bd4b0-fcb9f90]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]`

**Comment by APickledWalrus** [comment]
Skript 2.3.2 does not support 1.14.1. You can try the latest alpha release 2.4, but note that it is not bug free and will have some issues, so I wouldn’t use it on a production server.

You will also probably have to wait for an updated version of the split versions of Mundo
