### ISSUE TITLE
Stacktrace in console on startup

### ISSUE THREAD

**Issue by PhilFinachi** [MundoSK/MundoSK#4]
```
[14:58:49 INFO]: [MundoSK] Enabling MundoSK v1.7.5-BETA.7.149
[14:58:49 INFO]: [MundoSK] No worlds were assigned to load automatically
[14:58:49 INFO]: [MundoSK] Pie is awesome :D
[14:58:49 INFO]: [MundoSK] You are currently running a BETA version of MundoSK
[14:58:49 INFO]: [MundoSK] You should only run BETA versions of MundoSK on test servers unless Tlatoani or another reliable source has recommended otherwise
[14:58:49 INFO]: [MundoSK] You've discovered the amazing realm of ProtocolLib packet syntaxes!
[14:58:49 ERROR]: Error occurred while enabling MundoSK v1.7.5-BETA.7.149 (Is it up to date?)
java.lang.NoClassDefFoundError: com/pie/tlatoani/Tablist/Array/ArrayTablist
        at com.pie.tlatoani.Mundo.onEnable(Mundo.java:501) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.ClassNotFoundException: com.pie.tlatoani.Tablist.Array.ArrayTablist
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_111]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_111]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_111]
        ... 12 more
[14:58:49 INFO]: [MundoSK] Disabling MundoSK v1.7.5-BETA.7.149
[14:58:49 INFO]: [MundoSK] Closed all function sockets (if any were open)
[14:58:49 INFO]: [MundoSK] Successfully saved all world loaders
```

**Comment by TlatoaniHJ** [comment]
This has been fixed in the new beta (1.7.5-BETA.7.150)
