### ISSUE TITLE
1.12 support.

### ISSUE THREAD

**Issue by FUZIK** [MundoSK/MundoSK#5]
CraftBukkit version 1.12-pre6
ProtocolLib v4.3.0-SNAPSHOT-b370
Skript v2.2-dev28
MC: 1.12-pre6
on plugin startup:
```
[09:19:48 ERROR]: Error occurred while enabling MundoSK v1.7.5-BETA.7.136 (Is it up to date?)
java.lang.NoClassDefFoundError: com/comphenix/protocol/reflect/ObjectEnum
        at com.pie.tlatoani.Mundo.onEnable(Mundo.java:363) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.jar:git-Spigot-ac83d69-e13d119]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.jar:git-Spigot-ac83d69-e13d119]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.jar:git-Spigot-ac83d69-e13d119]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot-1.12.jar:git-Spigot-ac83d69-e13d119]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot-1.12.jar:git-Spigot-ac83d69-e13d119]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.12.jar:git-Spigot-ac83d69-e13d119]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.12.jar:git-Spigot-ac83d69-e13d119]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.12.jar:git-Spigot-ac83d69-e13d119]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.jar:git-Spigot-ac83d69-e13d119]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12.jar:git-Spigot-ac83d69-e13d119]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.reflect.ObjectEnum
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.12.jar:git-Spigot-ac83d69-e13d119]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.12.jar:git-Spigot-ac83d69-e13d119]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
        ... 12 more
```

**Comment by TlatoaniHJ** [comment]
This is not related to 1.12. It seems that new versions of ProtocolLib have removed code that MundoSK relied on, so you will need to downgrade to an older version (anything older than 4.3 should work).

**Comment by FUZIK** [comment]
Thanks! latest working build ProtocolLib 4.3.0-SNAPSHOT-b368. versions > 368 is not working because of "Rework packet type deprecation to actually work properly".  ;(
